# The bundle URL is a short-lived signed GCS URL, freshly generated by the
# deploy workflow on every run, so this resource shows an update-in-place
# diff on every apply even when the policy content hasn't changed.
resource "kubectl_manifest" "waf_policy" {
  yaml_body = yamlencode({
    apiVersion = "gateway.nginx.org/v1alpha1"
    kind       = "WAFPolicy"
    metadata = {
      name      = var.waf_policy_name
      namespace = kubernetes_namespace.nginx_gateway.metadata[0].name
      labels = {
        "app.kubernetes.io/managed-by" = "terraform"
        owner                          = local.resource_owner
      }
    }
    spec = {
      targetRefs = [
        {
          group = "gateway.networking.k8s.io"
          kind  = "Gateway"
          name  = local.gateway_name
        }
      ]
      type = "HTTP"
      policySource = {
        httpSource = {
          url = var.waf_bundle_url
        }
      }
    }
  })

  depends_on = [helm_release.ngf, kubectl_manifest.gateway]
}
